version: '3.7'

services:
  n8n:
    build: .
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./scripts:/scripts
    environment:
      - N8N_HOST=localhost
      - WEBHOOK_URL=http://localhost:5678

    restart: always
